name: Lint vision_opencv

on:
  pull_request:
  push:
    branches:
      - ros2

jobs: 
  # Linters applicable to C++ packages
  ament_lint_cpp:
    # Give each job a different name for better feedback
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-18.04
    strategy:
      # We want all linters to run even if one fails
      fail-fast: false 
      matrix:
        linter: [cppcheck, cpplint, uncrustify]
    steps:
    - uses: actions/checkout@v1
    - uses: ros-tooling/setup-ros2@0.0.11
    - uses: ros-tooling/action-ros2-lint@0.0.5
      with:
        linter: ${{ matrix.linter }}
        package-name: vision_opencv
